plugins {
    id("com.diffplug.spotless") version "5.6.1"
    id("com.vanniktech.maven.publish") version "0.34.0"
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'signing'
}
group = 'io.github.sasanlabs'
version = '1.0.3'

mavenPublishing {
    publishToMavenCentral()

    coordinates(
            "io.github.sasanlabs",
            "facade-schema",
            "1.0.3"
    )
    pom {
        name = "facade-schema"
        description = "Schema to fulfill the VulnerableApp-facade contract"
        url = "https://github.com/SasanLabs/facade-schema"

        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }

        developers {
            developer {
                id = "sasanlabs"
                name = "Karan Preet Singh Sasan"
                email = "preetkaran20@gmail.com"
            }
        }

        scm {
            connection = "scm:git:git://github.com/SasanLabs/facade-schema.git"
            developerConnection = "scm:git:ssh://github.com/SasanLabs/facade-schema.git"
            url = "https://github.com/SasanLabs/facade-schema"
        }
    }
}

signing {
    useGpgCmd()
    sign publishing.publications
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

javadoc {
    if (JavaVersion.current().isJava9Compatible()) {
        options.addBooleanOption('html5', true)
    }
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

spotless {
    java {
        clearSteps()
        googleJavaFormat().aosp()
    }
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.12.4'
}

test {
    useJUnitPlatform()
}